import Mathlib

/-
** 2.5 Proving Facts About Algebraic Structures **
https://leanprover-community.github.io/mathematics_in_lean/C02_Basics.html#proving-facts-about-algebraic-structures

In previous section, such as in 2.2 Proving identities in algebraic structures, we saw that many
common identities governing the real numbers hold in more general classes of algebraic structures,
such as commutative rings. We can use any axioms we want to describe an algebraic structure, not
just equations. For example, a partial order consists of a set with a binary relation that is
reflexive, transitive, and antisymmetric, like ≤ on the real numbers. Lean knows about partial
orders:
-/

-- Remember that we typically use Greek letters for types and capital letters for carriers of
-- algebraic structures like groups (G) or rings (R).
variable {α : Type*} [PartialOrder α]
variable (x y z : α)

#check x ≤ y
#check (le_refl x : x ≤ x)
#check (le_trans : x ≤ y → y ≤ z → x ≤ z)
#check (le_antisymm : x ≤ y → y ≤ x → x = y)

/-  Associated to any partial order, ≤, there is also a strict partial order, <, which acts
somewhat like < on the real numbers. Saying that x is less than y in this order is equivalent to
saying that it is less-than-or-equal to y and not equal to y.
-/

#check x < y
#check (lt_irrefl x : ¬ (x < x))
-- The symbol ¬ stands for "not"
#check (lt_trans : x < y → y < z → x < z)
#check (lt_of_le_of_lt : x ≤ y → y < z → x < z)
#check (lt_of_lt_of_le : x < y → y ≤ z → x < z)

example : x < y ↔ x ≤ y ∧ x ≠ y :=
-- The symbol ∧ stands for "and". The symbol ≠ abbreviates ¬ (x = y)
  lt_iff_le_and_ne

/- A lattice is a structure that extends a partial order with operations ⊓ and ⊔ that are analogous
to min and max on the real numbers. The characterizations of ⊓ and ⊔ justify calling them the
greatest lower bound and least upper bound, respectively. You can type them in VS code using
`\glb` and `\lub`. The symbols are also often called then infimum and the supremum, and Mathlib
refers to them as `inf` and `sup` in theorem names. To further complicate matters, they are also
often called meet and join. Therefore, if you work with lattices, you have to keep the following
dictionary in mind:

- ⊓ is the greatest lower bound, infimum, or meet.
- ⊔ is the least upper bound, supremum, or join.

Some instances of lattices include:

- `min` and `max` on any total order, such as the integers or real numbers with ≤
- ∩ and ∪ on the collection of subsets of some domain, with the ordering ⊆
- ∧ and ∨ on boolean truth values, with ordering x ≤ y if either x is false or y is true
- `gcd` and `lcm` on the natural numbers (or positive natural numbers), with the divisibility ordering, `∣`
- the collection of linear subspaces of a vector space, where the greatest lower bound is given by the intersection, the least upper bound is given by the sum of the two spaces, and the ordering is inclusion
- the collection of topologies on a set (or, in Lean, a type), where the greatest lower bound of two topologies consists of the topology that is generated by their union, the least upper bound is their intersection, and the ordering is reverse inclusion

You can check that, as with `min` / `max` and `gcd` / `lcm`, you can prove the commutativity and
associativity of the infimum and supremum using only their characterizing axioms, together with
`le_refl` and `le_trans`.

Using `apply le_trans` when seeing a goal `x ≤ z` is not a great idea. Indeed Lean has no way to
guess which intermediate element `y` we want to use. So `apply le_trans` produces three goals that
look like `x ≤ ?a`, `?a ≤ z` and `α` where `?a` (probably with a more complicated auto-generated
name) stands for the mysterious `y`. The last goal, with type `α`, is to provide the value of `y`.
It comes lasts because Lean hopes to automatically infer it from the proof of the first goal
`x ≤ ?a`. In order to avoid this unappealing situation, you can use the `calc` tactic to explicitly
provide `y`. Alternatively, you can use the `trans` tactic which takes `y` as an argument and
produces the expected goals `x ≤ y` and `y ≤ z`. Of course you can also avoid this issue by
providing directly a full proof such as `exact le_trans inf_le_left inf_le_right`, but this
requires a lot more planning.
-/

-- First, let's look at the theorems for lattices
variable {α : Type*} [Lattice α]
variable (x y z : α)

#check x ⊓ y
#check (inf_le_left : x ⊓ y ≤ x)
#check (inf_le_right : x ⊓ y ≤ y)
#check (le_inf : z ≤ x → z ≤ y → z ≤ x ⊓ y)
#check x ⊔ y
#check (le_sup_left : x ≤ x ⊔ y)
#check (le_sup_right : y ≤ x ⊔ y)
#check (sup_le : x ≤ z → y ≤ z → x ⊔ y ≤ z)

-- EXERCISE: good luck proving the following theorems
example : x ⊓ y = y ⊓ x := by
  apply le_antisymm
  -- Now we need to prove that x ⊓ y ≤ y ⊓ x and y ⊓ x ≤ x ⊓ y to show they are equal
  repeat
    -- Comments are for the first case but apply analogously to the second case (hence the repeat)
    apply le_inf  -- Split the goal into two subgoals: x ⊓ y ≤ y and x ⊓ y ≤ x
    apply inf_le_right  -- Prove x ⊓ y ≤ y
    apply inf_le_left  -- Prove x ⊓ y ≤ x

example : x ⊓ y ⊓ z = x ⊓ (y ⊓ z) := by
  apply le_antisymm
  · show x ⊓ y ⊓ z ≤ x ⊓ (y ⊓ z)
    apply le_inf
    · show x ⊓ y ⊓ z ≤ x
      trans x ⊓ y  -- Generate two goals: x ⊓ y ⊓ z ≤ x ⊓ y and x ⊓ y ≤ x
      apply inf_le_left  -- Direct proof of the first goal
      apply inf_le_left  -- Direct proof of the second goal
    · show x ⊓ y ⊓ z ≤ y ⊓ z
      apply le_inf
      · show x ⊓ y ⊓ z ≤ y
        trans x ⊓ y  -- Generate two goals: x ⊓ y ⊓ z ≤ x ⊓ y and x ⊓ y ≤ y
        apply inf_le_left  -- Direct proof of the first goal
        apply inf_le_right  -- Direct proof of the second goal
      · show x ⊓ y ⊓ z ≤ z
        apply inf_le_right
  · show x ⊓ (y ⊓ z) ≤ x ⊓ y ⊓ z
    apply le_inf
    · show x ⊓ (y ⊓ z) ≤ x ⊓ y
      apply le_inf
      · show x ⊓ (y ⊓ z) ≤ x
        apply inf_le_left
      · show x ⊓ (y ⊓ z) ≤ y
        trans y ⊓ z  -- Generate two goals: x ⊓ (y ⊓ z) ≤ y ⊓ z and y ⊓ z ≤ y
        apply inf_le_right  -- Direct proof of the first goal
        apply inf_le_left  -- Direct proof of the second goal
    · show x ⊓ (y ⊓ z) ≤ z
      trans y ⊓ z  -- Generate two goals: x ⊓ (y ⊓ z) ≤ y ⊓ z and y ⊓ z ≤ z
      apply inf_le_right  -- Direct proof of the first goal
      apply inf_le_right  -- Direct proof of the second goal

example : x ⊔ y = y ⊔ x := by
  apply le_antisymm  -- We need to prove x ⊔ y ≤ y ⊔ x and y ⊔ x ≤ x ⊔ y
  repeat
    -- Same for both objectives
    apply sup_le  -- Split the goal into two subgoals: x ≤ y ⊔ x and y ≤ y ⊔ x
    apply le_sup_right  -- Prove x ≤ y ⊔ x
    apply le_sup_left  -- Prove y ≤ y ⊔ x

example : x ⊔ y ⊔ z = x ⊔ (y ⊔ z) := by
  -- Buckle up, another long one!
  apply le_antisymm
  · show x ⊔ y ⊔ z ≤ x ⊔ (y ⊔ z)
    apply sup_le
    · show x ⊔ y ≤ x ⊔ (y ⊔ z)
      apply sup_le
      · show x ≤ x ⊔ (y ⊔ z)
        apply le_sup_left
      · show y ≤ x ⊔ (y ⊔ z)
        trans y ⊔ z  -- Generate two goals: y ≤ y ⊔ z and y ⊔ z ≤ x ⊔ (y ⊔ z)
        apply le_sup_left  -- Direct proof of the first goal
        apply le_sup_right -- Direct proof of the second goal
    · show z ≤ x ⊔ (y ⊔ z)
      trans y ⊔ z  -- Generate two goals: z ≤ y ⊔ z and y ⊔ z ≤ x ⊔ (y ⊔ z)
      apply le_sup_right  -- Direct proof of the first goal
      apply le_sup_right  -- Direct proof of the second goal
  · show x ⊔ (y ⊔ z) ≤ x ⊔ y ⊔ z
    apply sup_le
    · show x ≤ x ⊔ y ⊔ z
      trans x ⊔ y  -- Generate two goals: x ≤ x ⊔ y and x ⊔ y ≤ x ⊔ y ⊔ z
      apply le_sup_left  -- Direct proof of the first goal
      apply le_sup_left  -- Direct proof of the second goal
    · show y ⊔ z ≤ x ⊔ y ⊔ z
      apply sup_le
      · show y ≤ x ⊔ y ⊔ z
        trans x ⊔ y  -- Generate two goals: y ≤ x ⊔ y and x ⊔ y ≤ x ⊔ y ⊔ z
        apply le_sup_right  -- Direct proof of the first goal
        apply le_sup_left  -- Direct proof of the second goal
      · show z ≤ x ⊔ y ⊔ z
        apply le_sup_right

/- You can find these theorems in the Mathlib as `inf_comm`, `inf_assoc`, `sup_comm`, and
`sup_assoc`, respectively.
-/

#check inf_comm
#check inf_assoc
#check sup_comm
#check sup_assoc

-- EXERCISE: prove the absorption laws
theorem absorb1 : x ⊓ (x ⊔ y) = x := by
  apply le_antisymm
  · show x ⊓ (x ⊔ y) ≤ x
    apply inf_le_left
  · show x ≤ x ⊓ (x ⊔ y)
    apply le_inf
    · show x ≤ x
      apply le_refl
    · show x ≤ x ⊔ y
      apply le_sup_left

theorem absorb2 : x ⊔ x ⊓ y = x := by
  apply le_antisymm
  · show x ⊔ x ⊓ y ≤ x
    apply sup_le
    · show x ≤ x
      apply le_refl
    · show x ⊓ y ≤ x
      apply inf_le_left
  · show x ≤ x ⊔ x ⊓ y
    apply le_sup_left

-- These can be found in Mathlib with the names `inf_sup_self` and `sup_inf_self`.

#check inf_sup_self
#check sup_inf_self

/- A lattice that satisfies the additional identities x ⊓ (y ⊔ z) = (x ⊓ y) ⊔ (x ⊓ z) and
x ⊔ (y ⊓ z) = (x ⊔ y) ⊓ (x ⊔ z) is called a distributive lattice. Lean knows about these too:
-/
section
variable {α : Type*} [DistribLattice α]
variable (x y z : α)

#check (inf_sup_left x y z : x ⊓ (y ⊔ z) = x ⊓ y ⊔ x ⊓ z)
#check (inf_sup_right x y z : (x ⊔ y) ⊓ z = x ⊓ z ⊔ y ⊓ z)
#check (sup_inf_left x y z : x ⊔ y ⊓ z = (x ⊔ y) ⊓ (x ⊔ z))
#check (sup_inf_right x y z : x ⊓ y ⊔ z = (x ⊔ z) ⊓ (y ⊔ z))
end

/- The left and right versions are easily shown to be equivalent, given the commutativity of ⊓ and
⊔. It is a good exercise to show that not every lattice is distributive by providing an explicit
description of a nondistributive lattice with finitely many elements. It is also a good exercise to
show that in any lattice, either distributivity law implies the other:
-/

-- EXERCISE: prove the following theorem
section
variable {α : Type*} [Lattice α]
variable (a b c : α)

example (h : ∀ x y z : α, x ⊓ (y ⊔ z) = x ⊓ y ⊔ x ⊓ z) : a ⊔ b ⊓ c = (a ⊔ b) ⊓ (a ⊔ c) := by
  rw [h, inf_comm  (a ⊔ b), absorb1, inf_comm (a ⊔ b), h]
  rw [← sup_assoc, inf_comm c a, absorb2, inf_comm c b]

example (h : ∀ x y z : α, x ⊔ y ⊓ z = (x ⊔ y) ⊓ (x ⊔ z)) : a ⊓ (b ⊔ c) = a ⊓ b ⊔ a ⊓ c := by
  rw [h, sup_comm (a ⊓ b), absorb2, sup_comm (a ⊓ b), h]
  rw [← inf_assoc, sup_comm c a, absorb1, sup_comm c b]

end

/- It is possible to combine axiomatic structures into larger ones. For example, a strict ordered
ring consists of a ring together with a partial order on the carrier satisfying additional axioms
that say that the ring operations are compatible with the order:
-/
section
variable {R : Type*} [Ring R] [PartialOrder R] [IsStrictOrderedRing R]
variable (a b c : R)

#check (add_le_add_left : a ≤ b → ∀ c, c + a ≤ c + b)
#check (mul_pos : 0 < a → 0 < b → 0 < a * b)
-- The following one can be derived from `mul_pos` and the definition of <
#check (mul_nonneg : 0 ≤ a → 0 ≤ b → 0 ≤ a * b)

-- EXERCISE: prove the following theorems using only properties of rings, partial orders, and the
-- facts enumerated in the last two examples
theorem aux1 (h : a ≤ b) : 0 ≤ b - a := by
  rw [← sub_self a, sub_eq_add_neg, sub_eq_add_neg, add_comm, add_comm b]
  apply add_le_add_left h


theorem aux2 (h: 0 ≤ b - a) : a ≤ b := by
  rw [← add_zero a, ← sub_add_cancel b a, add_comm (b - a)]
  apply add_le_add_left h

example (h : a ≤ b) (h' : 0 ≤ c) : a * c ≤ b * c := by
  have h1 : 0 ≤ (b - a) * c := mul_nonneg (aux1 _ _ h) h'
  rw [sub_mul] at h1
  exact aux2 _ _ h1

end

/- Finally, here is one last example. A metric space consists of a set equipped with a notion of
distance, `dist x y`, mapping any pair of elements to a real number. The distance function is
assumed to satisfy the following axioms:
-/
section
variable {X : Type*} [MetricSpace X]
variable (x y z : X)

#check (dist_self x : dist x x = 0)
#check (dist_comm x y : dist x y = dist y x)
#check (dist_triangle x y z : dist x z ≤ dist x y + dist y z)

-- EXERCISE: prove the following theorem
-- Hint: use the `nonneg_of_mul_nonneg_left` theorem
#check nonneg_of_mul_nonneg_left

example (x y : X) : 0 ≤ dist x y :=by
  have : 0 ≤ dist x y + dist y x := by
    rw [← dist_self x]
    apply dist_triangle
  linarith [dist_comm x y]

end
